### ISSUE TITLE
Market Research

### ISSUE THREAD

**Issue by hellyworld** [ScriuCod-Python/mobile_collector#9]
search on web about similar projects to find ideas to implement on the project

- [x] GSMArena

- [x] compare.ro

**Comment by GhitaAlexandruIon** [comment]
![image](https://user-images.githubusercontent.com/49021460/98437731-9040ec80-20dc-11eb-97ca-7c17b39950d1.png)

**Comment by GhitaAlexandruIon** [comment]
compari.ro model

**Comment by GhitaAlexandruIon** [comment]
![image](https://user-images.githubusercontent.com/49021460/98793307-a661ec00-23ff-11eb-9027-b2abd57385ee.png)
gsm arena
